"""add unique id in integrations

Revision ID: 6bbb0ed8668e
Revises: 6dd757e58240
Create Date: 2021-04-12 16:42:01.200912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbb0ed8668e'
down_revision = '6dd757e58240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('unique_id', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'unique_id')
    # ### end Alembic commands ###
