"""user group migrations addition

Revision ID: 6dd757e58240
Revises: 1de5a8c20056
Create Date: 2021-04-09 22:23:04.839322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd757e58240'
down_revision = '1de5a8c20056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ### 
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
