"""empty message

Revision ID: 2de5a8c20056
Revises: 
Create Date: 2021-04-09 15:20:32.728695

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2de5a8c20056'
down_revision = 'guiugifugs'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
