"""integrations column changes

Revision ID: 529d6f7221aa
Revises: 6bbb0ed8668e
Create Date: 2021-04-12 23:54:14.950567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '529d6f7221aa'
down_revision = '6bbb0ed8668e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('unique_installation_id', sa.String(length=1000), nullable=True))
    op.drop_column('integrations', 'unique_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('unique_id', mysql.VARCHAR(length=1000), nullable=True))
    op.drop_column('integrations', 'unique_installation_id')
    # ### end Alembic commands ###
