"""client configuration col

Revision ID: bffbe44bfbc2
Revises: c28d9110572d
Create Date: 2021-04-22 16:42:45.023845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffbe44bfbc2'
down_revision = 'c28d9110572d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('configuration', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'configuration')
    # ### end Alembic commands ###
