"""integrations unique identifier name change

Revision ID: c28d9110572d
Revises: 529d6f7221aa
Create Date: 2021-04-13 17:47:47.202260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c28d9110572d'
down_revision = '529d6f7221aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('unique_installation_name', sa.String(length=1000), nullable=True))
    op.drop_column('integrations', 'unique_installation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('unique_installation_id', mysql.VARCHAR(length=1000), nullable=True))
    op.drop_column('integrations', 'unique_installation_name')
    # ### end Alembic commands ###
