"""rename vendor configuration

Revision ID: c5bd1ade54d7
Revises: fa137ca2e4f4
Create Date: 2021-05-03 20:04:03.084497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5bd1ade54d7'
down_revision = 'fa137ca2e4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    raise Exception()
    op.create_table('vendor_configuration',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_platform', sa.String(length=100), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.drop_table('vendor_configurations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_configurations',
    sa.Column('vendor_id', mysql.MEDIUMINT(display_width=9), autoincrement=True, nullable=False),
    sa.Column('vendor_platform', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('vendor_configuration', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('vendor_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('vendor_configuration')
    # ### end Alembic commands ###
