"""column remane to name

Revision ID: fa137ca2e4f4
Revises: bffbe44bfbc2
Create Date: 2021-05-03 15:35:01.729884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa137ca2e4f4'
down_revision = 'bffbe44bfbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('name', sa.String(length=1000), nullable=True))
    op.drop_column('integrations', 'unique_installation_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('unique_installation_name', mysql.VARCHAR(length=1000), nullable=True))
    op.drop_column('integrations', 'name')
    # ### end Alembic commands ###
